apiVersion: v1
kind: Service
metadata:
  name: mm-frontend
  labels:
    app: mm-frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      name: mm-frontend
  selector:
    app: mm-frontend
    tier: frontend
  type: ClusterIP
---
