apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mm-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mm-frontend
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75
---
