
name: CI/CD Pipeline

# Controls when the workflow will run
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEPLOYMENT_NAME: mm-frontend

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: np123dev/money_manager:${GITHUB_SHA:8} , np123dev/money_manager:latest
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}
      - name: Deploy
        run: |-
          kubectl apply -f .kubernetes/gke-mm-frontend-deployment.yml
          kubectl set image deployment/$DEPLOYMENT_NAME frontend=np123dev/money_manager:${GITHUB_SHA:8}
          kubectl rollout status deployment/$DEPLOYMENT_NAME
